version: "3.8"
name: redocs
services:
  redocs:
    container_name: redocs
    image: redocs:1.0.0
    build:
      context: .
      target: base
      dockerfile: ./docker/Dockerfile
    command: bash /start.sh
    # command: bash -c "tail -f /dev/null"
    restart: always
    env_file: .env
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - ./docker/start.sh:/start.sh
    extra_hosts:
      - host.docker.internal:host-gateway
