version: "3.8"
name: redocs
services:
  redocs_db:
    container_name: redocs_db
    image: mysql:8.0
    env_file: .env
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/backups:/backups
      - ./database/my.cnf:/etc/my.cnf
    extra_hosts:
      - host.docker.internal:host-gateway

  redocs_app:
    container_name: redocs_app
    image: redocs_app:1.0.0
    build:
      context: .
      target: base
      dockerfile: ./app/docker/Dockerfile
    command: bash /start.sh
    restart: always
    env_file: .env
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./app:/app
      - ./app/docker/start.sh:/start.sh
    extra_hosts:
      - host.docker.internal:host-gateway
